#Browser
browser=chrome

#practice Site URLs

saucedemo.url=https://www.saucedemo.com
demoqa.url=https://demoqa.com
the.internet.url=https://the-internet.herokuapp.com
orangehrm.url=https://opensource-demo.orangehrmlive.com

# SauceDemo Credentials
saucedemo.username=standard_user
saucedemo.password=secret_sauce

# OrangeHRM Credentials
orangehrm.username=Admin
orangehrm.password=admin123

reports.path=reports/ExtentReport.html
screenshots.path=reports/screenshots/

#Timeouts
implicit.wait=10
explicit.wait=15

page.load.timeout=30